export const REWARDS = {
  QUIZ_XP_PER_CORRECT: 10,
  CONVERSATION_COMPLETE_XP: 20,
};

export const QUIZ_CONFIG = {
  DEFAULT_COUNT: 10,
  ACCURACY_THRESHOLDS: { GREAT: 80, GOOD: 50 },
  REVIEW_RATIO: 0.6,
  WRONG_OPTIONS_COUNT: 3,
};

export const SRS_CONFIG = {
  SPEED_THRESHOLDS: { INSTANT: 3, QUICK: 8 },
  INITIAL_INTERVALS: [1, 3] as const,
  MASTERY_INTERVAL: 21,
  MIN_EASE_FACTOR: 1.3,
  INCORRECT_PENALTY: 0.2,
  REVIEW_DELAY_MINUTES: 10,
};

export const KANA_REWARDS = {
  STAGE_COMPLETE_XP: 30,
  QUIZ_PERFECT_XP: 20,
  QUIZ_PASS_XP: 10,
};

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 50,
};
